### ISSUE TITLE
同じユーザーで複数ログインするときのエラー

### ISSUE THREAD

**Issue by pahalce** [Piko-Piko-Pon-Taro/Remollege#106]
同じユーザーで多重にログインするとComponentからレスポンスが返ってきてないみたいなエラーになる。
コンソールにエラー文が出るまでにむっちゃ時間かかってページはずっとローディング中になるから何が起きてるかわかりにくい。

エラー文：
```text
Uncaught (in promise) ChunkLoadError: Loading chunk pages/buildings/_buildingId failed.
(timeout: http://localhost:3001/_nuxt/pages/buildings/_buildingId.js)
    at Function.requireEnsure [as e] (http://localhost:3001/_nuxt/runtime.js:896:26)
    at Function.fn.e (http://localhost:3001/_nuxt/runtime.js:177:40)
    at _7fd2f1dc (webpack-internal:///./.nuxt/router.js:26:92)
    at _callee$ (webpack-internal:///./.nuxt/utils.js:252:22)
    at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.eval [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:5:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:9)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:34:7)

**Comment by pahalce** [comment]
俺の環境だと
- 通常ウィンドウ→2人目でエラー発生
- シークレットウィンドウ→2人目まではなんともなくて3人目でエラー発生

ってかんじだった

**Comment by tsuyoshi628** [comment]
現状google認証のみ使ってて再現しないので閉じまっす
