### ISSUE TITLE
存在しないユーザーでのログイン時のエラーハンドリング(auth.js＆フロントのメッセージ表示)

### ISSUE THREAD

**Issue by pahalce** [Piko-Piko-Pon-Taro/Remollege#72]
エラー文：
POST /auth/login/ - - ms - -
Executing (default): SELECT id, name, email, password, img, createdAt, updatedAt FROM Users AS User WHERE User.email = 'test@gmail.com' LIMIT 1;
(node:81) UnhandledPromiseRejectionWarning: Error: login failed
    at /src/api/routes/auth.js:91:22
    at allFailed (/src/api/node_modules/passport/lib/middleware/authenticate.js:107:18)
    at attempt (/src/api/node_modules/passport/lib/middleware/authenticate.js:180:28)
    at Strategy.strategy.fail (/src/api/node_modules/passport/lib/middleware/authenticate.js:302:9)
    at verified (/src/api/node_modules/passport-local/lib/strategy.js:82:30)
    at Strategy._verify (/src/api/passport.js:27:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:81) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).

**Comment by tsuyoshi628** [comment]
#76 で対応する。
